"""Shared training routines for runnable model-version scripts."""

from __future__ import annotations

from pathlib import Path

import pandas as pd
from sklearn.dummy import DummyClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC

from .data_loading import load_csv
from .datasets import stratified_literal_split
from .inference import build_submission
from .metrics import classification_metrics
from .paths import METRICS_DIR, PREDICTIONS_DIR, SUBMISSIONS_DIR, ensure_project_dirs
from .preprocessing import build_category_dataset, normalize_literal
from .reporting import add_report_note, log_experiment
from .utils import save_json, set_seed


def make_classical_pipeline(model_family: str) -> Pipeline:
    """Create a compact sklearn model for the requested family."""
    if model_family == "majority":
        return Pipeline(
            [
                ("tfidf", TfidfVectorizer(preprocessor=normalize_literal)),
                ("clf", DummyClassifier(strategy="most_frequent")),
            ]
        )
    if model_family == "logreg":
        return Pipeline(
            [
                (
                    "tfidf",
                    TfidfVectorizer(
                        preprocessor=normalize_literal,
                        analyzer="char_wb",
                        ngram_range=(2, 5),
                        min_df=1,
                        max_features=200_000,
                        sublinear_tf=True,
                    ),
                ),
                (
                    "clf",
                    LogisticRegression(
                        max_iter=2000,
                        class_weight=None,
                        solver="liblinear",
                    ),
                ),
            ]
        )
    return Pipeline(
        [
            (
                "tfidf",
                TfidfVectorizer(
                    preprocessor=normalize_literal,
                    analyzer="char_wb",
                    ngram_range=(2, 5),
                    min_df=1,
                    max_features=200_000,
                    sublinear_tf=True,
                ),
            ),
            ("clf", LinearSVC(C=2.0, max_iter=10_000, random_state=42)),
        ]
    )


def run_sklearn_model_version(
    model_id: str,
    model_family: str,
    train: bool = True,
    evaluate: bool = True,
    predict: bool = True,
    make_submission: bool = True,
    dry_run: bool = False,
) -> dict[str, object]:
    """Train, evaluate, predict, and log a runnable sklearn model version."""
    ensure_project_dirs()
    set_seed(42)

    if dry_run:
        summary = {
            "model_id": model_id,
            "model_family": model_family,
            "status": "dry_run_ok",
        }
        save_json(summary, METRICS_DIR / f"{model_id}_dry_run.json")
        return summary

    codification = load_csv("codification")
    category_df = build_category_dataset(codification)
    x_train, x_val, y_train, y_val = stratified_literal_split(category_df)

    model = make_classical_pipeline(model_family)
    if train:
        model.fit(x_train, y_train)

    metrics = {}
    if evaluate:
        val_pred = model.predict(x_val)
        metrics = classification_metrics(y_val, val_pred)
        save_json(metrics, METRICS_DIR / f"{model_id}.json")
        pd.DataFrame(
            {"Literal": x_val.values, "y_true": y_val.values, "y_pred": val_pred}
        ).to_csv(PREDICTIONS_DIR / f"{model_id}_validation_predictions.csv", index=False)
        log_experiment(model_id, metrics, "Generated by runnable model-version script.")

    if predict or make_submission:
        model.fit(category_df["Literal"], category_df["y_category"])
        leaderboard = load_csv("leaderboard")
        leaderboard_pred = model.predict(leaderboard["Literal"])
        pred_df = build_submission(leaderboard, leaderboard_pred, include_literal=True)
        pred_df.to_csv(PREDICTIONS_DIR / f"{model_id}_leaderboard_predictions.csv", index=False)
        if make_submission:
            pred_df.to_csv(SUBMISSIONS_DIR / f"{model_id}_submission.csv", index=False)

    add_report_note(
        f"Model {model_id}",
        f"Ran `{model_id}` with family `{model_family}`. Metrics are stored in `outputs/metrics/`.",
    )
    return {"model_id": model_id, "metrics": metrics}

